# Generated by Django 2.2 on 2020-01-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_delete_orderproduct'),
        ('product', '0002_auto_20200122_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Ціна')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='Кількість')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_order', to='cart.Order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_product', to='product.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Продукти замовлень',
            },
        ),
    ]
