# Generated by Django 2.2 on 2020-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_options',
            field=models.IntegerField(choices=[(1, 'Free shipping'), (2, 'Express shipping'), (3, 'Courier shipping'), (4, 'Free express shipping')], default=1, verbose_name='Shipping options'),
        ),
    ]
