# Generated by Django 2.2 on 2020-01-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200122_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_options',
            field=models.IntegerField(blank=True, choices=[(1, 'Free shipping'), (2, 'Express shipping'), (3, 'Courier shipping'), (4, 'Free express shipping')], default=1, verbose_name='Shipping options'),
        ),
    ]
