# Generated by Django 2.2 on 2020-01-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
