# Generated by Django 2.2 on 2020-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Цена')),
                ('active_more', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Типы доставки',
            },
        ),
    ]
