# Generated by Django 2.2 on 2020-01-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_typedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='cart.TypeDelivery', verbose_name='доставка'),
        ),
    ]
