# Generated by Django 2.2 on 2020-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200124_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedelivery',
            name='active_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
